
language: en

stylesheets:
- /css/vv13
- //at.alicdn.com/t/font_438575_w9o3rescwyp919k9.css

scripts:
- /js/vv13.js

less:
  compress: true
  paths:
    - source/css/vv13.less

github: https://github.com/vv13
rss: /atom.xml
ama_url: https://github.com/vv13/ama
